name: demo-xstatic
version: 0.1.0.0
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/haskell-xstatic
category: JavaScript

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  # how to make template haskell file-embed be safe?
  - -Wno-missing-safe-haskell-mode -Wno-unsafe

dependencies:
  - base
  - bytestring
  - xstatic
  - xstatic-htmx
  - xstatic-sortable
  - xstatic-remixicon
  - xstatic-tailwind
  - warp
  - wai
  - http-types

executable:
  source-dirs: .
  main: Demo.hs
