name: xstatic-pdfjs
version: 3.4.120
synopsis: PDF Reader in JavaScript.
description: PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5.
homepage: https://github.com/mozilla/pdf.js/
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/haskell-xstatic
category: JavaScript
extra-source-files:
  - CHANGELOG.md
  - data/*.gz

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  # how to make template haskell file-embed be safe?
  - -Wno-missing-safe-haskell-mode -Wno-unsafe

dependencies:
  - base <5
  - xstatic-th

library:
  source-dirs: src/
