name: xstatic-codemirror
version: 6.0.1.1
synopsis: Extensible Code Editor
description: Extensible Code Editor.
homepage: https://codemirror.net/
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/haskell-xstatic
category: JavaScript
license: MIT
extra-source-files:
  - CHANGELOG.md
  - data/*.gz

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  # how to make template haskell file-embed be safe?
  - -Wno-missing-safe-haskell-mode -Wno-unsafe

dependencies:
  - base <5
  - xstatic-th

library:
  source-dirs: src/
