name: xstatic-ace
version: 1.23.4
synopsis:  Ace (Ajax.org Cloud9 Editor)
description: |
  Ace is a standalone code editor written in JavaScript.

  To update, run:

    rsync -a ~/src/github.com/ajaxorg/ace-builds/src-noconflict/ data/
    find data/ -name "*.js" -exec gzip -f -9 {} \;

homepage: https://ace.c9.io
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/haskell-xstatic
category: JavaScript
extra-source-files:
  - CHANGELOG.md
  - data/*.gz
  - data/snippets/*.gz

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  # how to make template haskell file-embed be safe?
  - -Wno-missing-safe-haskell-mode -Wno-unsafe

dependencies:
  - base <5
  - xstatic-th

library:
  source-dirs: src/
