name: xstatic-sakura
version: 1.4.1.0
synopsis: A minimal css framework/theme
description: A minimal css framework/theme.
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/haskell-xstatic
category: JavaScript
license-file: LICENSE.txt
extra-source-files:
  - CHANGELOG.md

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  # how to make template haskell file-embed be safe?
  - -Wno-missing-safe-haskell-mode -Wno-unsafe

dependencies:
  - base <5
  - xstatic

library:
  source-dirs: src/
