name: xstatic-xterm
version: 5.3.0
synopsis: A terminal for the web
description: A terminal for the web.
homepage: https://xtermjs.org
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/haskell-xstatic
category: JavaScript
license: MIT
extra-source-files:
  - CHANGELOG.md
  - data/*.gz

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  # how to make template haskell file-embed be safe?
  - -Wno-missing-safe-haskell-mode -Wno-unsafe

dependencies:
  - base <5
  - xstatic-th

library:
  source-dirs: src/
