name: xstatic-otjs
version: 0.0.15
synopsis: Collaborative editing using operational transformation
description: Collaborative editing using operational transformation.
homepage: https://github.com/Operational-Transformation/ot.js
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/haskell-xstatic
category: JavaScript
license: MIT
extra-source-files:
  - CHANGELOG.md
  - data/*.gz

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  # how to make template haskell file-embed be safe?
  - -Wno-missing-safe-haskell-mode -Wno-unsafe

dependencies:
  - base <5
  - xstatic-th

library:
  source-dirs: src/
