name: lucid2-xstatic
version: 0.1.0
synopsis: Lucid2 helper for XStatic
description: Use this library to add XStaticFile to your Html.
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/haskell-xstatic
category: JavaScript
extra-source-files:
  - CHANGELOG.md

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  - -Wno-missing-safe-haskell-mode -Wno-unsafe

dependencies:
  - base <5
  - lucid2
  - xstatic
  - text

library:
  source-dirs: src/
